config/routes.rb
Rails.application.routes.draw do
  resources :attendees
  resources :study_sessions
  resources :admin
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  resources :users, only: [:show] do
    resources :study_sessions, only: [:show, :index]
    resources :attendees, only: [:index, :show]
  end

#  get '/users/:user_id/study_sessions_by_grade', to: 'study_sessions#by_grade', as: 'study_sessions_by_grade'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendee.rb
class Attendee < ApplicationRecord
  belongs_to :student, class_name: "User", foreign_key: :user_id
  belongs_to :study_session
end

app/models/study_session.rb
class StudySession < ApplicationRecord
  belongs_to :teacher, class_name: "User", foreign_key: :user_id
  has_many :attendees
  has_many :students, through: :attendees, foreign_key: :user_id

  SUBJECTS = [
    "ELA", "Quidditch", "Honors ELA", "Math", "Honors Math", "Social Studies", "Science", "French", "Spanish", "Band", "Journalism", "Drama", "Art"
  ]

  validates :grade, presence: true
  validates :content, presence: true
  validates :date, presence: true
  validates :time, presence: true

  def self.subjects
    SUBJECTS
  end

  def self.by_grade(grade)
    self.where(grade: grade)
  end

  def self.by_student(student)
    sessions_attending = []
    Attendee.where(user_id: student.id).each do |attendee|
      sessions_attending << attendee.study_session
    end
    self.where(id: sessions_attending)
  end

  def self.by_date(date)
    self.where(date: date)
  end

  def self.search(search)
    self.where(date: search)
  end

  def self.present_or_future
    self.ordered_by_date.where("date > ?", Date.today)
  end

  def self.ordered_by_date
    self.order(:date)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :recoverable, :rememberable, :trackable, :validatable,
  #:confirmable, :lockable, :timeoutable
  devise :database_authenticatable, :registerable, :omniauthable, omniauth_providers: [:google_oauth2]

  enum role: [:student, :teacher, :admin]
  has_many :study_sessions
  has_many :students, through: :study_sessions
  has_many :attendees

  def attending?(study_session)
    Attendee.where(user_id: self.id, study_session_id: study_session.id).exists?
  end

  def attendance_record(study_session)
    Attendee.find_by(user_id: self.id, study_session_id: study_session.id)
  end

  def self.attending_by_date(date)
    students_attending = []
    StudySession.by_date(date).each do |study_session|
      students_attending += study_session.students
    end
    self.where(id: students_attending)
  end

  def self.from_omniauth(auth)
    self.where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.name = auth.info.name
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authorize_admin

  def index
    if params[:search]
      @study_sessions = StudySession.by_date(params[:search])
    end
  end

  def show
  end

  private
  def authorize_admin
    current_user.admin?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include Pundit
  # below before_action stopped firing.  Do not understand why.
  before_action :user_signed_in?
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def after_sign_in_path_for(resource)
    if current_user.provider == 'google_oauth2'
      edit_user_registration_path
    else
      request.env['omniauth.origin'] || study_sessions_path
    end
  end

  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/attendees_controller.rb
class AttendeesController < ApplicationController
  before_action :set_attendee, only: [:destroy]

  def index
    @attendees = policy_scope(Attendee)
  end

  def create
    @attendee = Attendee.find_or_initialize_by(user_id: current_user.id, study_session_id: params[:study_session_id])
    authorize @attendee
    if @attendee.save
      render json: @attendee
    else
      flash[:alert] = "Could not complete your request"
      render '/welcome/index'
    end
  end

  def destroy
    authorize @attendee
    if @attendee.destroy
      # redirect_to user_study_sessions_path(current_user)
      render body: nil, status: :no_content
    else
      flash[:alert] = "Could not delete this attendance record."
      render '/welcome/index'
    end
  end

  private

  def set_attendee
    @attendee = Attendee.find(params[:id])
  end
end

app/controllers/study_sessions_controller.rb
class StudySessionsController < ApplicationController
  before_action :set_study_session, only: [:show, :edit, :update, :destroy]
  def index
    @study_session = StudySession.new
    if params[:search]
      @study_sessions = StudySession.search(params[:search])
    else
      @study_sessions = policy_scope(StudySession)
    end
  end

  def show
    render json: @study_session
  end

  def new
    @study_session = StudySession.new
    authorize @study_session
    # render layout: false
    respond_to do |format|
      format.html
      format.js { render layout: false}
    end
  end

  def create
    @study_session = current_user.study_sessions.build(study_session_params)
    authorize @study_session
    if @study_session.save
      # redirect_to user_study_sessions_path(current_user)
      render json: @study_session, status:201
    else
      flash[:alert] = "Study session did not save."
      render "index"
    end
  end

  def edit
    authorize @study_session
    respond_to do |format|
      format.html
      format.js { render layout: false}
    end
    # render json: @study_session, status:201
    # render layout: false
  end

  def update
    authorize @study_session
    if @study_session.update(study_session_params)
      render json: @study_session, status:201
    else
      flash[:alert] = "Study session did not save."
      render "index"
    end
  end

  def destroy
    authorize @study_session
    @study_session.destroy
    # redirect_to user_study_sessions_path(current_user)
  end

  private
  def study_session_params
    params.require(:study_session).permit(:subject, :content, :date, :time, :grade)
    # params.permit(study_session: {})
  end

  def set_study_session
    @study_session = StudySession.find(params[:id])
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    @user = User.from_omniauth(request.env['omniauth.auth'])
      if @user.persisted?
        flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
        sign_in_and_redirect @user, event: :authentication
      else
        session['devise.google_data'] = request.env['omniauth.auth'].except(:extra) # Removing extra as it can overflow some session stores
        redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
      end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  private

  def update_resource(resource, params)
    if current_user.provider == "google_oauth2"
      params.delete("current_password")
      resource.update_without_password(params)
    else
      resource.update_with_password(params)
    end
  end

  def after_update_path_for(resource)
    study_sessions_path
  end

  def sign_up_params
    params.require(:user).permit(:name, :current_grade, :role, :email, :password, :password_confirmation)
  end

  def account_update_without_password_params
    params.require(:user).permit(:name, :current_grade, :role, :email)
  end

  def account_update_params
    params.require(:user).permit(:name, :current_grade, :role, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :user_signed_in?, only: :index
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendees_helper.rb
module AttendeesHelper
end

app/helpers/study_sessions_helper.rb
module StudySessionsHelper
  def subjects
    StudySession.subjects
  end
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/admin/index.html.erb
<h2> Welcome <%= current_user.name  %> to the Come On In Admin Dashboard</h2>


<%= form_tag study_sessions_path, :method => 'get' do %>
  <%= text_field_tag :search, "Out of Order"%>
  <%= submit_tag "Search Study Sessions", class: 'btn btn-xs'%>
    <br><br>
<% end %>
<%= form_tag admin_index_path, :method => 'get' do %>
  <%= date_field_tag :search %>
  <%= submit_tag "All Attending Students", class: 'btn btn-xs'%>
<% end %>
<br><br>
<%= button_to "All Study Sessions",  study_sessions_path, :method => 'get', class: 'btn btn-xs' %>
<br><br>
<% if @study_sessions %>
<%= render :partial => 'study_sessions/teacher_show', :collection => @study_sessions, :as => 'study_session' %>
<% end %>

app/views/attendees/index.html.erb
<h2>Hello  <%= current_user.name %> </h2>
<h3>Here are your study sessions</h3>
<p class="separators">_______________________________________________</p>
<% @attendees.each do |attendance_record| %>
  <%= render :partial => 'study_sessions/study_session', :locals => {study_session: attendance_record.study_session} %>
<% end %>

app/views/layouts/_errors.html.erb
<%= content_tag(:div, flash[:error], :id => "flash_error") if flash[:error] %>
<%= content_tag(:div, flash[:notice], :id => "flash_notice") if flash[:notice] %>
<%= content_tag(:div, flash[:alert], :id => "flash_alert") if flash[:alert] %>

app/views/layouts/_navigation.html.erb
    <!-- Brand and toggle get grouped for better mobile display
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div> -->

<ul class="nav nav-tabs">
<li><%= link_to "Home", root_path %></li>
<% if current_user %>
  <% if current_user.admin? %>
    <li><%= link_to "Admin Home", admin_index_path %></li>
  <% elsif current_user.teacher? %></li>
    <!-- <li><%= link_to "Your Study Sessions", user_study_sessions_path(current_user)%></li> -->
    <li><%= link_to "Create New Study Session", "", :id => "create" %></li>
  <% else %>
    <li><%= link_to "Your Study Sessions", user_attendees_path(current_user) %></li>
    <li><%= link_to "Available Study Sessions", study_sessions_path %></li>
  <% end %>
  <li> <%= link_to "Update User",  edit_user_registration_path %> </li>
  <li><%= link_to "Sign Out",  destroy_user_session_path, :method => 'delete' %></li>
<% else %>
  <li><%= link_to "Sign In", user_session_path %></li>
  <li><%= link_to "Sign in with Google", user_google_oauth2_omniauth_authorize_path %></li>
  <li><%= link_to "Sign Up", new_user_registration_path %></li>
<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ComeOnIn</title>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application', "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>

  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <%= render "layouts/navigation" %>
      </div><!-- /.container-fluid -->
    </nav>
    <div id="main-container" class="container-fluid">
      <div id="main-content" >
        <%= render "layouts/errors" %>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/study_sessions/_form.html.erb
<%= form_for study_session, :html => {class: "form"} do |f| %>
  <div class="field form-group">
    <%= f.label :subject, :class => "col-xs-3 control-label" %>
    <div class="col-xs-9">
      <%= f.select :subject, subjects.map {|subject| subject},:class => "form-control"  %>
    </div>
  </div>
  <div class="field form-group">
    <%= f.label :grade, :class => "col-xs-3 control-label" %>
    <div class="col-xs-9">
      <%= f.select :grade, [6, 7, 8] %>
    </div>
  </div>
  <div class="field form-group">
    <%= f.label :content, "Purpose of study session:", :class => "col-xs-3 control-label" %>
    <div class="col-xs-9">
      <%= f.text_field :content %>
    </div>
  </div>
  <div class="field form-group">
    <%= f.label :date, :class => "col-xs-3 control-label" %>
    <div class="col-xs-9">
      <%= f.date_field :date %>
    </div>
  </div>
  <div class="field form-group">
    <%= f.label :time, :class => "col-xs-3 control-label" %>
    <div class="col-xs-9">
      <%= f.text_field :time, :value => study_session.time %>
    </div>
  </div>
  <div class="action form-group">
    <div class="col-xs-offset-3 col-xs-9">
      <%= f.submit :class => 'btn btn-xs' %>
    </div>
  </div>
<% end %>

app/views/study_sessions/_student_navigation.html.erb
<% if current_user.attending?(study_session) %>
  <%= button_to "Attending - Change Attendance", "", form_class: "student", class: 'btn btn-xs student', data: {attendee_id: current_user.attendance_record(study_session).id} %>
<% else %>
  <%= button_to "Attend", "",  form_class: "student", class: 'btn btn-xs' %>
<% end %>

app/views/study_sessions/_study_session.html.erb
<div class="row" data-id="<%= study_session.id %>">
  <div class="col">
    <h3><%= study_session.subject %> | <%= study_session.teacher.name %> | <%= study_session.grade %></h3>
    <p><%= study_session.content %> |
    <%= study_session.date.strftime("%A, %b %d, %Y") %> at <%= study_session.time %></p>
    <div class="attendees"></div>
  </div>
  <div class="col">
    <!-- <form data-id="<%= study_session.id %>">

    </form> -->
    <% if current_user.teacher? || current_user.admin? %>
      <%= render :partial => "study_sessions/teacher_navigation", :locals => {study_session: study_session} %>
    <% else %>
      <%= render :partial => "study_sessions/student_navigation", :locals => {study_session: study_session} %>
    <% end %>
  </div>
</div>

<!-- <div class="row" data-id="<%= study_session.id %>">
  <div class="col">
    <p><%= link_to study_session.content, study_session_path(study_session) %> |
    <%= study_session.date.strftime("%A, %b %d, %Y") %> at <%= study_session.time %></p>
  </div>
  <div class="col">
  </div>
</div> -->


<p class="separators">_______________________________________________</p>

app/views/study_sessions/_teacher_navigation.html.erb
<div class="row" >
  <!-- <%= button_to "Edit Study Session", edit_study_session_path(study_session), :method => 'get', class: 'btn btn-xs' %> -->
  <%= button_to "Show Attendees", "#", :data => { id: study_session.id}, form_class: "show-attendees", class: 'btn btn-info btn-xs' %>
</div><div class="row" >
  <!-- <%= button_to "Edit Study Session", edit_study_session_path(study_session), :method => 'get', class: 'btn btn-xs' %> -->
  <%= button_to "Edit Study Session", "#", form_class: 'teacher', class: 'btn btn-xs', :id => study_session.id  %>
</div>
<div class="row">
<!-- if multiple popups continue, may have to change javascript_include_tag to read data-turbolinks-eval => false -->
  <%= button_to "Delete Study Session", "#", :method => 'delete', :data => {confirm: "Are you sure?", id: study_session.id}, form_class: "teacher", class: 'btn btn-danger btn-xs' %>
</div>

app/views/study_sessions/_teacher_show.html.erb
<h3> <%= study_session.teacher.name %> | <%= study_session.grade %> | <%= study_session.content %> </h3>
<% if study_session.students.count > 0 %>
  <h4>Students Attending</h4>
  <ul>
  <% study_session.students.each do |student| %>
    <li><%= student.name %> | <%= student.current_grade %></li>
  <% end %>
  </ul>
<% else %>
  <p>No students have signed up for this study session.</><p>
<% end %>

app/views/study_sessions/edit.html.erb
<%= render :partial => 'form', :locals => {study_session: @study_session} %>

app/views/study_sessions/index.html.erb
<h2>Hello  <%= current_user.name %>! </h2>
<% if current_user.teacher? || current_user.admin? %>
  <div id="study_session_form"></div>
<% end %>

<h3>Here are your study sessions:</h3>
<p class="separators">_______________________________________________</p>
<div id="new_session"></div>
<%= render :collection => @study_sessions, :partial => 'study_sessions/study_session', :as => 'study_session' %>

app/views/study_sessions/new.html.erb
<%= render :partial => 'form', :locals => {study_session: @study_session} %>

app/views/study_sessions/show.html.erb
<% if current_user.teacher? || current_user.admin? %>
  <%= render :partial => 'teacher_show', :locals => {study_session: @study_session} %>
<% else %>
  <%= render :partial => 'study_session', :locals => {study_session: @study_session} %>
<% end %>
<br><br>

app/views/welcome/index.html.erb
<h2> Welcome <%= current_user.name if current_user %> to Come On In! </h2>
<p class="separators">_______________________________________________</p>